name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
        cache: gradle

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew :module:assembleRelease

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Zygisk-ImGui-Menu
        path: out/magisk_module_release/
